development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pays_dev
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pays_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pays_prod
  pool: 5
  username: root
  password:
